# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  target 'ShareExtension' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end

  # https://stackoverflow.com/a/73839370/827047
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
  
  # Added by Simon (2022-03-11)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Seems to be needed for multiple dependencies. Builds otherwise fail.
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      
       # https://github.com/flutter-webrtc/flutter-webrtc/issues/713#issuecomment-1001058073
      if target.name == "flutter_webrtc" || target.name == "WebRTC-SDK"
        #config.build_settings['ARCHS']='arm64'
        # Confirmed that this is fixing an issue when building from Android Studio to simulator
        config.build_settings['ONLY_ACTIVE_ARCH']='YES'
      end
    end
  end
end
